version: "3.9"
services:
  dbprod01:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name:  dbprod01
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_TCP_PORT: 3306
    volumes:
      - dbprod01-data:/var/lib/mysql
      - ./_tool/db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./_tool/db/sql:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
  # app:
  #   image: mh-api-srv
  #   depends_on:
  #     - mh-api-dbsrv01
  #   build:
  #     args:
  #       - target=dev
  #   environment:
  #     ENV: DEV
  #     PORT: 8080
  #     DB_HOST: "mh-api-dbsrv01:3306"
  #     DB_USER: mh-api
  #     DB_PASSWORD: P@ssw0rd
  #     DB_NAME: mh-api
  #     SECRET_KEY: 4y2rLkn1j+p979YcG0GlSGYr7zM7tKUrl7O/BzrcnTQ=
  #     TOKEN_LIFETIME: 3600
  #     USER: admin
  #     PASSWORD: password
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '8080:8080'
volumes:
  dbprod01-data: